name: Deploy to atthost server
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: cluedo-checker

    name: Build And Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: NPM Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/websites/cluedo-checker'
          EXCLUDE: "/dist/, /node_modules/"